name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Fazendo checkout do código
      uses: actions/checkout@v2

    - name: Construir e publicar a imagem no dockerhub
      uses: docker/build-push-action@v1.1.0
      with:
        username: liviafeitosa
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: liviafeitosa/argocd-nodeapp
        tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Fazendo checkout do código
      uses: actions/checkout@v2
      with:
        repository: liviafeitosa/argocd-nodeapp-config
        token: ${{ secrets.TOKEN_GITHUB }}

    - name: Instalar o Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize_version: v3.6.1

    - name: Atualizando os valores da imagem
      run: |
        ls
        cd kubernetes
        kustomize edit set imagem imagem=liviafeitosa/nodeapp:${{ github.sha }}

    - name: Criando commit tag da imagem
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Deploy Action"
        git add .
        git commit -m "Mudando a tag da imagem"
        git pull --rebase
        git push
